& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'LogFileCheck.Name' = 'LogFileCheck'
'AddsValidation.Name' = 'AddsValidation'
'AldsValidation.Name' = 'AldsValidation'
'Cancel.Name' = 'Cancel'
'MemberServer.Name' = 'MemberServer'
'ComputerName.Name' = 'ComputerName'
'LogFile.Name' = 'LogFile'
'ComputerNameCheck.Name' = 'ComputerNameCheck'
'AddsInstallStatus.Name' = 'AddsInstallStatus'
'Next.Name' = 'Next'
'Description.Name' = 'Description'
'ValidateButton.Name' = 'ValidateButton'
'LogFileCreatedSuccess.Name' = 'LogFileCreatedSuccess'
'Validation.Name' = 'Validation'
'SysPrepCancel.Name' = 'SysPrepCancel'
'ComputerCheck.Name' = 'ComputerCheck'
'DomainCheck.Name' = 'DomainCheck'
'UserName.Name' = 'UserName'
'Computer.Name' = 'Computer'
'Title.Name' = 'Title'
'Domain.Name' = 'Domain'
'Description.Text' = 'Click ''Validate'' to confirm the machine this tool is running on is a domain-joined member server and can install the necessary tools. The computer must be a member server and the user must have permission to build Active Directory and Certificate Template objects.'
'UsernameCheck.Name' = 'UsernameCheck'
'Validate.Name' = 'Validate'
'AdcsValidation.Name' = 'AdcsValidation'
'$this.Name' = 'SystemPrep'
'FailedValidation.Name' = 'FailedValidation'
'DomainName.Name' = 'DomainName'
'MemberServerStatus.Name' = 'MemberServerStatus'
'DomainStatus.Name' = 'DomainStatus'
'MemberServerCheck.Name' = 'MemberServerCheck'
'SysPrepNext.Name' = 'SysPrepNext'
'AdcsInstalled.Name' = 'AdcsInstalled'
'User.Name' = 'User'
}
}