& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'Cancel.Name' = 'Cancel'
'Next.Name' = 'Next'
'Title.Name' = 'Title'
'Description.Name' = 'Description'
'Description.Text' = 'Click ''Validate'' to confirm the machine this tool is running on is a domain-joined member server and can install the necessary tools. The computer must be a member server and the user must have permission to build Active Directory and Certificate Template objects.'
'Domain.Name' = 'Domain'
'MemberServer.Name' = 'MemberServer'
'ComputerName.Name' = 'ComputerName'
'AldsValidation.Name' = 'AldsValidation'
'AdcsValidation.Name' = 'AdcsValidation'
'UserName.Name' = 'UserName'
'LogFile.Name' = 'LogFile'
'Validation.Name' = 'Validation'
'AdcsInstalled.Name' = 'AdcsInstalled'
'AddsInstallStatus.Name' = 'AddsInstallStatus'
'MemberServerStatus.Name' = 'MemberServerStatus'
'DomainStatus.Name' = 'DomainStatus'
'ComputerNameCheck.Name' = 'ComputerNameCheck'
'UsernameCheck.Name' = 'UsernameCheck'
'LogFileCreatedSuccess.Name' = 'LogFileCreatedSuccess'
'$this.Name' = 'SystemPrep'
'Validate.Name' = 'Validate'
'FailedValidation.Name' = 'FailedValidation'
'User.Name' = 'User'
'DomainName.Name' = 'DomainName'
'Computer.Name' = 'Computer'
'ValidateButton.Name' = 'ValidateButton'
}
}